# Site settings
title: Serg Pokrovskyy - Private Card
description: Serg Pokrovskyy - Private Card
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Serg Pokrovskyy
user_description:
user_title: Entrepreneur, Software Architect, Student
email: s.pokrovskyy@gmail.com
twitter_username: spokrovskyy
github_username:  pokrovskyy

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
